# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: Run all in parallel
    cmds:
      - task: fmt
      - task: checks

  checks:
    internal: true
    deps:
      - build
      - test
      - lint

  build:
    desc: Build
    cmds:
      - go build ./...

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run lint
    cmds:
      - go vet ./...

  fmt:
    desc: Run format
    cmds:
      - go fmt ./...

  inspector:
    desc: Run MCP inspector
    cmds:
      - npx @modelcontextprotocol/inspector
